
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Chart.Name}}-pvc-data
  namespace: {{ .Values.namespaceName }}
spec:
  volumeName: {{.Chart.Name}}-pv-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.pvc.requests.storage | quote}}